apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 3
    spot: true

# eksctl create cluster --config-file=eks.yaml # create eks cluster
# kubectl get nodes -o wide # get nodes
# kubectl get pods -n kube-system # get pods in kube-system namespace
# kubectl get svc -n kube-system # get services in kube-system namespace

