apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    course: DevOps  
    trainer: John
spec:
  containers:
  - name: nginx-container 
    image: nginx
    ports:
    - containerPort: 80

# command to run this pod
# kubectl apply -f 03-labels.yaml

