apiVersion: v1
kind: Pod
metadata:
  name: resource-pod 
  labels:
    app: resource
spec:
  containers:
  - name: resource-container
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi" # 64 Megabytes
        cpu: "250m" # 250 milliCPU
      limits:
        memory: "128Mi"
        cpu: "500m"

# kubectl apply -f 06-resources.yaml # create pod 

# kubectl get pods # get pods in default namespace
# kubectl get pods -n roboshop # get pods in roboshop namespace
# kubectl describe pod hello-pod -n roboshop # describe pod in roboshop namespace


# kubectl delete pod hello-pod -n roboshop # command to delete pod in roboshop namespace
