apiVersion: v1
kind: Secret
metadata:
  name: devops-secret
type: Opaque
data:
  username: YWRtaW4= # encoded value of admin, encryption type is base64
  password: cGFzc3dvcmQ= # encoded value of password, encryption type is base64
spec:
  containers:

# generating base64 value 
# echo -n "admin" | base64
# echo -n "password" | base64

# decoding base64 value
# echo -n "YWRtaW4=" | base64 -d
# echo -n "cGFzc3dvcmQ=" | base64 -d

