apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-container
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: devops-secret

# first run 09-secrets.yaml to create the secret
# command to run the pod
# kubectl apply -f 10-pod-secrets.yaml

